version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: assemblyscript
    versions:
    - 0.17.14
    - 0.18.16
    - 0.18.18
    - 0.18.19
    - 0.18.21
    - 0.18.22
    - 0.18.23
    - 0.18.24
    - 0.18.25
    - 0.18.27
    - 0.18.28
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
  - dependency-name: svelte-check
    versions:
    - 1.1.30
    - 1.1.31
    - 1.1.32
    - 1.1.33
    - 1.1.34
    - 1.1.35
    - 1.1.36
    - 1.2.0
    - 1.2.1
    - 1.2.3
    - 1.2.4
  - dependency-name: "@assemblyscript/loader"
    versions:
    - 0.18.0
    - 0.18.10
    - 0.18.11
    - 0.18.12
    - 0.18.13
    - 0.18.14
    - 0.18.3
    - 0.18.4
    - 0.18.6
    - 0.18.7
    - 0.18.9
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
    - 11.1.1
  - dependency-name: "@rollup/plugin-typescript"
    versions:
    - 8.1.0
    - 8.1.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: sirv-cli
    versions:
    - 1.0.10
